USE next_gen_db;


INSERT INTO exam_categories (id, name, description, icon) 
SELECT '62a25515-7ef5-4d45-b313-3ec2c4dfd6f1', 'CTET', 'Central Teacher Eligibility Test', '📚'
FROM DUAL
WHERE NOT EXISTS (SELECT id FROM exam_categories WHERE name = 'CTET');

SET @cat_id = (SELECT id FROM exam_categories WHERE name = 'CTET' LIMIT 1);
INSERT INTO subjects (id, category_id, name)
SELECT 'ede76bba-0c6f-477c-a1d8-d541e050ba5b', @cat_id, 'Child Development and Pedagogy'
FROM DUAL
WHERE NOT EXISTS (SELECT id FROM subjects WHERE name = 'Child Development and Pedagogy' AND category_id = @cat_id);
SET @subj_id = (SELECT id FROM subjects WHERE name = 'Child Development and Pedagogy' AND category_id = @cat_id LIMIT 1);

-- Insert Questions

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('ccfa9c10-00ec-488e-9929-8b861c8b783e', @cat_id, @subj_id, 'Which of the following statements denotes the relationship between development and learning correctly?', '{"A": "Learning and development are parallel processes not interrelated.", "B": "Developmental pace lags behind the learning process.", "C": "Learning and development are interrelated and interdependent.", "D": "Development is completely independent of learning."}', 'C', 'Development and learning have a bidirectional relationship. According to modern educational psychology and thinkers like Vygotsky, learning and development are dynamic, complexly interconnected, and influence each other throughout life.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('39df9470-a9fe-41ed-b63b-759d9687faa0', @cat_id, @subj_id, 'According to Jean Piaget, during which stage of cognitive development does a child develop ''Object Permanence''?', '{"A": "Sensorimotor Stage", "B": "Pre-operational Stage", "C": "Concrete Operational Stage", "D": "Formal Operational Stage"}', 'A', 'Object permanence—the understanding that objects continue to exist even when they cannot be seen or heard—typically develops during the sensorimotor stage (birth to 2 years), usually around 8 months of age.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('50e42aa5-666a-4868-9a50-b30bb4c733b4', @cat_id, @subj_id, 'According to Lev Vygotsky, what is the primary cause of cognitive development?', '{"A": "Biological maturation", "B": "Social interaction", "C": "Stimulus-response pairing", "D": "Equilibration"}', 'B', 'Lev Vygotsky''s Socio-Cultural theory emphasizes that human intelligence originates in society or culture, and social interaction is the foundational element driving cognitive growth.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('1266892e-0575-4554-928e-754704d4a561', @cat_id, @subj_id, 'A teacher provides hints and cues to students while they solve a complex puzzle. In Vygotsky''s theory, this temporary assistance is called:', '{"A": "Reinforcement", "B": "Egocentric Speech", "C": "Scaffolding", "D": "Conditioning"}', 'C', 'Scaffolding is a process through which a teacher or a More Knowledgeable Other (MKO) offers temporary support to a learner in the Zone of Proximal Development (ZPD) to help them accomplish a task they cannot do independently.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('cb2a93a6-9749-443a-95d7-4b63c69329d0', @cat_id, @subj_id, 'In Kohlberg''s theory of moral development, at which stage do individuals make moral decisions based on universal ethical principles and human rights?', '{"A": "Punishment and Obedience orientation", "B": "Good boy-Nice girl orientation", "C": "Social contract orientation", "D": "Universal Ethical Principle orientation"}', 'D', 'The Universal Ethical Principle orientation represents Stage 6 (Post-Conventional Level), where moral reasoning is based on abstract principles of justice, equality, and human rights, independent of laws or social agreements.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('53e0c678-38e5-4f20-9aa2-b4b5c92cc5be', @cat_id, @subj_id, 'Which of the following is a characteristic of a Progressive Classroom?', '{"A": "Focus on rote memorization and passive listening.", "B": "Flexible seating arrangements and emphasis on collaborative learning.", "C": "Frequent use of rewards and punishments to control behavior.", "D": "Strict textbook-centric teaching with no scope for activities."}', 'B', 'Progressive education (advocated by John Dewey) emphasizes learning by doing, hands-on activities, critical thinking, flexible seating, and cooperative or democratic group learning.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('d278d448-8a10-4c8f-8f53-a3cb49dff183', @cat_id, @subj_id, 'Child-centered pedagogy means:', '{"A": "Giving primacy to children''s voices, experiences, and active participation.", "B": "Asking children to copy down everything the teacher writes on the board.", "C": "The complete control of the classroom by the teacher.", "D": "Setting strict curriculum and testing schedules for children."}', 'A', 'Child-centered pedagogy values the active nature, inherent capabilities, interests, and lived experiences of the child, shifting the role of the teacher from an authority figure to a facilitator.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('aec41188-18c8-45ef-a487-c99c9935a70e', @cat_id, @subj_id, 'According to Howard Gardner''s theory of Multiple Intelligences, a person who can understand and manage the emotions, motivations, and desires of OTHER people possesses:', '{"A": "Intrapersonal Intelligence", "B": "Interpersonal Intelligence", "C": "Spatial Intelligence", "D": "Naturalistic Intelligence"}', 'B', 'Interpersonal intelligence deals with understanding and interacting effectively with other people. Intrapersonal intelligence, by contrast, is the capacity to understand oneself.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('abb3f040-5b7a-4020-8e82-e1ccc76afecb', @cat_id, @subj_id, 'Continuous and Comprehensive Evaluation (CCE) primarily emphasizes:', '{"A": "Testing of cognitive abilities only at the end of the term.", "B": "How learning can be observed, recorded, and improved.", "C": "Comparing learners with one another using rigid ranking systems.", "D": "Rote recall of facts under exam pressure."}', 'B', 'CCE aims to evaluate all aspects of a child''s development continuously, focusing on formative processes that map out how learning can be recorded, tracked, and remediated to improve student outcomes.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('96a68163-66e9-40b7-8c47-612cd68ec51b', @cat_id, @subj_id, 'An inclusive classroom is one where:', '{"A": "Only gifted and talented students are given admission.", "B": "Students from diverse backgrounds and different abilities learn together under a single roof.", "C": "Disabled students are taught separately in specialized rooms.", "D": "Teachers follow uniform instruction methods regardless of individual differences."}', 'B', 'Inclusive education means educating all students—regardless of any physical, social, emotional, linguistic, or cognitive differences—together in regular classrooms with appropriate structural support.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('c3c5a28d-0428-4a1e-b9dc-cf88b11ac13e', @cat_id, @subj_id, 'A child has persistent difficulty in reading text, spelling words correctly, and decoding passages. The child is likely showing signs of:', '{"A": "Dysgraphia", "B": "Dyscalculia", "C": "Dyslexia", "D": "ADHD"}', 'C', 'Dyslexia is a specific neurological learning disability characterized by difficulties with accurate and fluent word recognition, reading, and spelling.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('a4d7c6db-6c44-4c7e-a7b4-758c879ead0e', @cat_id, @subj_id, 'Which of the following is an effective strategy to reduce gender stereotyping and gender role conformity among school children?', '{"A": "Forming separate gender-based rows or seating arrangements in class.", "B": "Encouraging stereotypical toys (e.g., dolls for girls, trucks for boys).", "C": "Discussions on non-stereotypical gender roles (e.g., male chefs, female pilots).", "D": "Assigning physical tasks only to boys and cleaning tasks to girls."}', 'C', 'Open classroom discussions about counter-stereotypical examples challenge traditional gender boundaries and allow children to perceive gender roles in an egalitarian manner.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('67e035cf-df05-404c-a3e0-f19e593377b4', @cat_id, @subj_id, 'To foster critical thinking in her classroom, a teacher should encourage students to:', '{"A": "Memorize definitions given word-for-word in the textbook.", "B": "Analyze a problem from multiple perspectives and find open-ended solutions.", "C": "Accept information from authoritative sources blindly.", "D": "Avoid working on complex tasks and complete worksheets quickly."}', 'B', 'Critical thinking involves analyzing, evaluating, looking at multi-perspective data, and breaking down a problem to arrive at logic-backed, open-ended conclusions rather than rote replication.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('e6ae368b-afb9-4517-9b8c-870601372a66', @cat_id, @subj_id, 'Which of the following statements about errors made by children during the learning process is correct?', '{"A": "Errors indicate that children are intellectually deficient.", "B": "Errors are windows into children''s thinking and are a natural part of learning.", "C": "Errors must be heavily penalized immediately to stop recurrence.", "D": "Errors have no relevance in pedagogical planning."}', 'B', 'Errors are not signs of failure; they are diagnostic windows that show how children construct alternative conceptual structures. They are a necessary step in cognitive maturation.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('a188dc47-2245-4d7b-87bd-48f5e20f03fc', @cat_id, @subj_id, 'According to Piaget, the process of adjusting or changing existing mental schemas in response to new information is called:', '{"A": "Assimilation", "B": "Accommodation", "C": "Organization", "D": "Egocentrism"}', 'B', 'Accommodation is modifying existing schemas or creating new ones because new information does not fit neatly into pre-existing schemas. (Fitting new info into existing schemas without modification is Assimilation).', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('387d7322-708a-4e12-8817-bc13951853bd', @cat_id, @subj_id, 'When a child learns to use a pen to write after having mastered holding a large ball, this progression from gross motor skills to fine motor skills exemplifies:', '{"A": "Cephalocaudal Principle", "B": "Proximodistal Principle", "C": "Principle of Interrelation", "D": "Principle of Discontinuity"}', 'B', 'The Proximodistal principle states that development proceeds from the center of the body outward. Control over large muscles (gross motor) happens before fine motor precision in fingers.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('55b715cc-c9c2-4c39-b54f-b4676c1131e9', @cat_id, @subj_id, 'Which type of motivation is driven by internal rewards, such as personal satisfaction, curiosity, or the joy of learning?', '{"A": "Extrinsic Motivation", "B": "Intrinsic Motivation", "C": "Social Motivation", "D": "Fear-based Motivation"}', 'B', 'Intrinsic motivation arises from within the individual. The task itself provides joy or satisfying value, requiring no external tangible reward like scores, trophies, or money.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('34404d8e-71da-4ac6-968b-3f3e691ecff4', @cat_id, @subj_id, 'Which of the following is an example of an ''authentic task'' for assessing student learning in environmental studies?', '{"A": "A multiple-choice quiz on definitions of pollution.", "B": "Designing an actionable neighborhood garbage disposal or recycling plan.", "C": "Writing down five sentences about trees from a textbook page.", "D": "Labeling a diagram of the water cycle from memory."}', 'B', 'An authentic task reflects real-world complexities and contexts, asking students to apply their knowledge creatively to address actual scenarios, rather than reproducing rote test metrics.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('eb566690-073f-4503-9a3c-513215c8cbbe', @cat_id, @subj_id, 'The concept of ''Zone of Proximal Development'' (ZPD) indicates the area:', '{"A": "Where a child cannot learn even with extensive expert support.", "B": "Between what a learner can do independently and what they can do with assistance.", "C": "Where intellectual developmental slowing occurs permanently.", "D": "Exclusive to solitary reflex conditioning."}', 'B', 'ZPD represents the golden learning zone: tasks that a child cannot complete alone yet can master when given targeted, structured guidance from an expert peer or instructor.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('b66755a3-304f-4a03-bdd8-ec5d991f5ab8', @cat_id, @subj_id, 'A teacher treats intelligence as a static, fixed trait fixed at birth. This belief can lead to:', '{"A": "A growth mindset in students.", "B": "Higher expectations for lower-performing groups.", "C": "A fixed mindset that discourages effort and learning resilience.", "D": "More activity-centered lesson planning."}', 'C', 'Viewing intelligence as a fixed trait (Entity theory) fosters a fixed mindset. Students believe effort is useless if talent is predetermined, leading to low academic resilience when facing hurdles.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('48fe0c9a-f765-4109-b082-c16e1972ba2e', @cat_id, @subj_id, 'In a multilingual country like India, a teacher should view the native languages spoken by children as:', '{"A": "A barrier or asset deficit to teaching English.", "B": "An administrative nuisance to be suppressed in school.", "C": "A rich resource for classroom instruction and language mapping.", "D": "A symptom of speech deficiency."}', 'C', 'National educational mandates (like NEP) highlight multilingualism as a cognitive and socio-cultural asset. Children''s home languages should be used as pedagogical resources.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('1aa2f9d5-877b-462d-86b4-1ddcfb1ea31c', @cat_id, @subj_id, 'Formative assessment is fundamentally designed to:', '{"A": "Grade and classify students into distinct sections.", "B": "Provide ongoing feedback to optimize teaching and learning paths.", "C": "Rank students for district awards at the close of an academic cycle.", "D": "Determine pass/fail metrics on report cards."}', 'B', 'Formative assessment is ''assessment for learning.'' It occurs dynamically during the instruction period to inform both the teacher and learner on changes needed to optimize current comprehension.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('8291cc6e-1061-4f14-b0b9-451114ab146f', @cat_id, @subj_id, 'According to the Cephalocaudal principle of development, growth proceeds from:', '{"A": "Head to toe", "B": "Center to periphery", "C": "General to specific", "D": "Simple to complex"}', 'A', 'The Cephalocaudal principle states that biological growth and developmental control follow a head-to-toe pattern. A child gains control of their neck and upper upper chest before coordinating legs and walking.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('973022ce-87ea-4456-8d93-a10a3b86bb0d', @cat_id, @subj_id, 'Which of the following practices promotes meaningful learning in classrooms?', '{"A": "Imposing uniform, rigid punishment systems.", "B": "Cooperative learning environments and linking concepts to real life.", "C": "Continuous comparative analysis of student marks on notice boards.", "D": "Exclusive reliance on teacher-led lecture methodology."}', 'B', 'Meaningful learning occurs when new concepts are systematically linked to contextual, real-world schemas, driven further by collective discussion and cooperative problem-solving.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('87504f5d-ce9b-47cf-91a6-86f2563f6673', @cat_id, @subj_id, 'A student who exhibits extreme restlessness, struggles to pay attention for more than a few minutes, and acts impulsively may have:', '{"A": "Dyscalculia", "B": "Autism Spectrum Disorder", "C": "Attention Deficit Hyperactivity Disorder (ADHD)", "D": "Visual Impairment"}', 'C', 'ADHD is characterized by persistent patterns of inattention, hyperactivity, and impulsivity that interfere significantly with academic performance, executive functioning, and developmental tasks.', 1.00, 0.00);

-- Insert Model Set
INSERT INTO model_sets (id, title, description, category_id, question_ids, time_limit_minutes, total_marks, status)
VALUES ('eee25a8d-0635-4d2e-a47f-7eca981e4b2a', 'CTET CDP 25-Question Mock Set', 'A comprehensive 25-questions mock model MCQ set covering CTET CDP syllabus.', @cat_id, '["ccfa9c10-00ec-488e-9929-8b861c8b783e", "39df9470-a9fe-41ed-b63b-759d9687faa0", "50e42aa5-666a-4868-9a50-b30bb4c733b4", "1266892e-0575-4554-928e-754704d4a561", "cb2a93a6-9749-443a-95d7-4b63c69329d0", "53e0c678-38e5-4f20-9aa2-b4b5c92cc5be", "d278d448-8a10-4c8f-8f53-a3cb49dff183", "aec41188-18c8-45ef-a487-c99c9935a70e", "abb3f040-5b7a-4020-8e82-e1ccc76afecb", "96a68163-66e9-40b7-8c47-612cd68ec51b", "c3c5a28d-0428-4a1e-b9dc-cf88b11ac13e", "a4d7c6db-6c44-4c7e-a7b4-758c879ead0e", "67e035cf-df05-404c-a3e0-f19e593377b4", "e6ae368b-afb9-4517-9b8c-870601372a66", "a188dc47-2245-4d7b-87bd-48f5e20f03fc", "387d7322-708a-4e12-8817-bc13951853bd", "55b715cc-c9c2-4c39-b54f-b4676c1131e9", "34404d8e-71da-4ac6-968b-3f3e691ecff4", "eb566690-073f-4503-9a3c-513215c8cbbe", "b66755a3-304f-4a03-bdd8-ec5d991f5ab8", "48fe0c9a-f765-4109-b082-c16e1972ba2e", "1aa2f9d5-877b-462d-86b4-1ddcfb1ea31c", "8291cc6e-1061-4f14-b0b9-451114ab146f", "973022ce-87ea-4456-8d93-a10a3b86bb0d", "87504f5d-ce9b-47cf-91a6-86f2563f6673"]', 30, 25.00, 'published');
