USE next_gen_db;


SET @cat_id = (SELECT id FROM exam_categories WHERE name = 'CTET' LIMIT 1);
SET @subj_id = (SELECT id FROM subjects WHERE name = 'Child Development and Pedagogy' AND category_id = @cat_id LIMIT 1);
SET @vac_id = (SELECT id FROM vacancies WHERE title = 'CTET Complete Preparation' AND category_id = @cat_id LIMIT 1);

-- Insert Questions

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('50662fb9-9462-4a1a-b19c-293151fa4609', @cat_id, @subj_id, 'According to Jean Piaget, at which stage of cognitive development does a child begin to think logically about concrete events?', '{"A": "Sensorimotor stage", "B": "Pre-operational stage", "C": "Concrete operational stage", "D": "Formal operational stage"}', 'C', 'During the Concrete Operational Stage (7-11 years), children develop the capacity to think logically, but only about concrete, tangible objects and real-world events that they can perceive directly.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('4ef54e11-c1bb-4061-9845-8ce6a9033568', @cat_id, @subj_id, 'According to Lev Vygotsky, the concept of ''Zone of Proximal Development'' (ZPD) refers to:', '{"A": "The point at which a child can perform a task completely independently.", "B": "The distance between what a learner can do independently and what they can do with expert guidance.", "C": "The fixed intelligence quotient (IQ) score measured by standard tests.", "D": "The genetic limitation of developmental potential."}', 'B', 'ZPD is the dynamic learning zone representing tasks that are too difficult for a child to master alone but can be learned with the help and scaffolding of a More Knowledgeable Other (MKO).', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('db4d9648-d1a8-405b-ba8e-6645a74ac740', @cat_id, @subj_id, 'In Kohlberg''s theory of moral development, a child whose moral reasoning is based on avoiding punishment and obeying authority is at the:', '{"A": "Pre-conventional morality level", "B": "Conventional morality level", "C": "Post-conventional morality level", "D": "Social-contract orientation level"}', 'A', 'The first level of Kohlberg''s theory is Pre-conventional morality, where the first stage is obedience and punishment orientation. Rules are viewed as fixed and absolute strictly to avoid negative physical consequences.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('ed6c5c54-f89a-406b-b009-1b2ddc0f9215', @cat_id, @subj_id, 'A child consistently reads ''saw'' as ''was'' and confuses letters like ''b'' and ''d''. These symptoms are characteristic of which learning disability?', '{"A": "Dysgraphia", "B": "Dyslexia", "C": "Dyscalculia", "D": "ADHD"}', 'B', 'Dyslexia is a specific language-based learning disability that primary impairs a person''s ability to read, decode words fluently, and recognize letter patterns accurately.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('360d6500-ca5d-4e2b-a988-79aab077c7f5', @cat_id, @subj_id, 'The fundamental goal of ''Inclusive Education'' in an Indian school setup is to:', '{"A": "Establish separate special schools for children with physical challenges.", "B": "Educate all children together in the regular classroom regardless of physical, cognitive, or socio-economic differences.", "C": "Focus exclusively on regularizing curriculum for gifted and high-performing students.", "D": "Enforce strict uniform lecturing standards across all districts."}', 'B', 'Inclusive education means restructuring the educational framework so that all children, including those with special needs (CWSN) and diverse backgrounds, study together equitably in regular classrooms.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('9aa42237-0393-40ee-a6fe-54bf47eb77aa', @cat_id, @subj_id, 'John Dewey, the father of Progressive Education, emphasized that schools should be a reflection of society and learning should happen through:', '{"A": "Passive listening and strict structural discipline.", "B": "Rote memorization of prescribed standard textbooks.", "C": "Learning by doing, hands-on activities, and collaborative problem-solving.", "D": "Frequent teacher-led standardized testing."}', 'C', 'Progressive education rejects passive instruction. It prioritizes experiential learning (''learning by doing''), critical thinking, and social collaboration inside the classroom ecosystem.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('5cb32f68-5403-49f5-84f5-4435b1b89c8d', @cat_id, @subj_id, 'What is the primary objective of Formative Assessment conducted during the instructional process?', '{"A": "To rank and classify students at the end of the academic year.", "B": "To provide ongoing, diagnostic feedback to improve both teaching methodologies and student learning.", "C": "To award grades and terminal pass/fail certificates.", "D": "To accelerate syllabus completion under administrative time constraints."}', 'B', 'Formative assessment is ''assessment for learning.'' It occurs concurrently with instruction to diagnose learning gaps and adjust active teaching strategies to optimize understanding dynamically.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('493c24b8-55c5-4741-a673-47b2863f7c44', @cat_id, @subj_id, 'Child-Centered Pedagogy means giving primacy to:', '{"A": "The complete authoritative control of the classroom by the teacher.", "B": "Children''s experiences, voices, interests, and active participation.", "C": "Mechanical writing assignments and copying text from the board.", "D": "Segregating children based on their initial IQ levels."}', 'B', 'Child-centered pedagogy keeps the learner at the focus, respecting individual differences, innate capacities, and utilizing their active participation as the engine of learning.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('0890de02-c932-4be9-98ff-1532dde45c7e', @cat_id, @subj_id, 'Which of the following is considered the primary agency of socialization for a child?', '{"A": "School and educational institutions", "B": "Mass media and internet portals", "C": "Family and immediate neighborhood", "D": "Religious and political organizations"}', 'C', 'The family is the primary agency of socialization. It is the initial social circle where a child learns foundational behaviors, values, language, and cultural norms from infancy.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('ea46b3a7-42ed-4624-a7f0-088f8fca27a3', @cat_id, @subj_id, 'During the Pre-operational stage, a child focuses on only one aspect of a situation while neglecting others. Piaget termed this cognitive limitation as:', '{"A": "Centration", "B": "Object Permanence", "C": "Reversibility", "D": "Conservation"}', 'A', 'Centration is the tendency to focus on one salient feature of an object or problem while excluding other relevant elements. This prevents children in the pre-operational stage from understanding conservation.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('01085758-8659-41a8-9dd0-74c471801390', @cat_id, @subj_id, 'Which of the following scenarios is an example of Intrinsic Motivation?', '{"A": "Studying hard to win a cash prize from parents.", "B": "Completing homework out of fear of getting punished by the teacher.", "C": "Reading a science textbook out of pure curiosity and personal interest in the topic.", "D": "Participating in a race solely to show off athletic superiority to peers."}', 'C', 'Intrinsic motivation originates from within an individual. The activity itself is inherently rewarding, satisfying, or joyful, and does not require external incentives or pressure.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('fc3310df-a6ce-42c2-8cdc-76491d70f034', @cat_id, @subj_id, 'According to Howard Gardner''s theory of Multiple Intelligences, architects and sculptors generally possess high levels of:', '{"A": "Logical-mathematical Intelligence", "B": "Visual-spatial Intelligence", "C": "Bodily-kinesthetic Intelligence", "D": "Interpersonal Intelligence"}', 'B', 'Visual-spatial intelligence involves the capacity to think in images, orient objects accurately in 3D mental schemas, and recreate spatial arrangements effectively.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('a6450918-5ea4-4a53-b220-d91d748e6386', @cat_id, @subj_id, 'In Piaget''s theory, the process of modifying existing cognitive structures (schemas) or creating new ones because new info conflicts with old ideas is called:', '{"A": "Assimilation", "B": "Accommodation", "C": "Objectification", "D": "Egocentrism"}', 'B', 'Accommodation involves modifying internal mental structures or creating entirely new ones when new environmental information cannot be cleanly assimilated into pre-existing schemas.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('a6f83dff-4c52-43e3-93b0-b14342ef6410', @cat_id, @subj_id, 'The ongoing nature-nurture debate in developmental psychology centers around the relative contribution of:', '{"A": "Home environment versus school environment.", "B": "Heredity (genetic makeup) and Environment (experiential context).", "C": "Physical nutrition versus mental stimulation.", "D": "Maternal care versus paternal interaction."}', 'B', 'Nature denotes biological heredity, genetic inheritance, and maturation. Nurture signifies environmental influences, cultural context, upbringing, and learning experiences.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('b3394659-174f-4346-812a-4260a5f4c735', @cat_id, @subj_id, 'A major point of divergence between the cognitive theories of Jean Piaget and Lev Vygotsky lies in their view of:', '{"A": "Whether children are passive or active learners.", "B": "The functional relationship between Language and Thought.", "C": "The fundamental existence of cognitive development altogether.", "D": "The value of observational learning mechanisms."}', 'B', 'Piaget argued that thought precedes language and that language is a tool for expressing egocentric thought. Vygotsky argued that language and thought initially develop separately and merge around age three, with language driving cognitive internalization.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('88cc9384-8256-4658-b63f-a3292c755344', @cat_id, @subj_id, 'An educator assigns domestic tasks like decoration to girls and technical tasks like computer maintenance to boys. This instructional bias reflects:', '{"A": "Gender Equity", "B": "Gender Stereotyping", "C": "Gender Constancy", "D": "Gender Empowerment"}', 'B', 'Assigning specific behaviors, expectations, or limitations to individuals based purely on historical gender roles rather than individual capabilities constitutes gender stereotyping.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('a2268a7a-bb1b-44be-acaa-94d0380c1954', @cat_id, @subj_id, 'In Continuous and Comprehensive Evaluation (CCE), the term ''Comprehensive'' specifically implies the assessment of:', '{"A": "Only academic (scholastic) subjects via pen-and-paper tests.", "B": "Both scholastic (academic) and co-scholastic (holistic/co-curricular) domains of a child''s development.", "C": "Extensive cognitive memorization traits evaluated weekly.", "D": "Strict non-verbal motor milestones during early childhood."}', 'B', 'Comprehensive evaluation focuses on the holistic development of the child, integrating academic achievements (scholastic) alongside behavioral values, life skills, physical health, and arts (co-scholastic).', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('9d8177c9-55ed-4258-a826-d7cbe0cfd78e', @cat_id, @subj_id, 'Who proposed the ''Two-Factor Theory of Intelligence'' consisting of a general factor (''g'') and specific factors (''s'')?', '{"A": "Howard Gardner", "B": "Charles Spearman", "C": "Louis Thurstone", "D": "Robert Sternberg"}', 'B', 'Charles Spearman introduced the Two-Factor Theory of Intelligence in 1904, identifying a general intellectual capacity (''g factor'') underlying all mental actions and task-specific traits (''s factors'').', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('089f46df-83e8-4375-9f74-0effeb75f8e3', @cat_id, @subj_id, 'The ''Operant Conditioning'' theory of learning, which posits that behavior is shaped by its consequences (reinforcement and punishment), was developed by:', '{"A": "Ivan Pavlov", "B": "B.F. Skinner", "C": "Edward Thorndike", "D": "Albert Bandura"}', 'B', 'B.F. Skinner developed Operant Conditioning, demonstrating that behavioral frequency changes depending on positive reinforcement, negative reinforcement, or punitive outcomes following the actions.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('8a7e61da-ae04-40a2-853b-8fa3b8d5e240', @cat_id, @subj_id, 'A student struggles with mathematical operations, recognizing numerical symbols, and calculating values. The student is likely experiencing:', '{"A": "Dyslexia", "B": "Dyscalculia", "C": "Dysgraphia", "D": "Aphasia"}', 'B', 'Dyscalculia is a neurological learning disability that severely limits an individual''s capacity to comprehend numbers, learn mathematical operations, perform computations, and grasp arithmetic patterns.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('f89feeac-5dd0-4687-8985-1484157fefd2', @cat_id, @subj_id, 'Which of the following evaluation strategies aligns best with Child-Centered Pedagogy?', '{"A": "A single terminal board exam evaluating memorization.", "B": "Continuous and qualitative assessments like student portfolios, self-assessments, and projects.", "C": "Rigid multiple-choice testing applied uniformly at the start of a semester.", "D": "Comparing and displaying student rank lists publicly."}', 'B', 'Child-centered pedagogy requires multidimensional, non-threatening evaluation techniques like portfolios and peer reviews that capture progress organically rather than through a static high-stakes exam.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('e8ca9d8a-aeb0-49db-b069-21ee4f91e7ea', @cat_id, @subj_id, 'In an Inclusive Classroom, which of the following practices should a teacher strictly avoid?', '{"A": "Implementing Individualized Education Programs (IEPs) for learners.", "B": "Segregating and placing children with disabilities in separate rows or sections.", "C": "Utilizing diverse audio-visual instructional aids.", "D": "Modifying physical infrastructure to ensure barrier-free access."}', 'B', 'Inclusive principles demand full social integration. Isolating or segregating children based on their differences creates psychological barriers and violates the fundamental ethics of inclusive education.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('6c320511-0875-42bf-8775-307fcb86ea52', @cat_id, @subj_id, 'Which statement regarding the principles of human growth and development is factually accurate?', '{"A": "Development is a discontinuous, random sequence of events.", "B": "Development is a continuous lifelong process that runs from conception to death.", "C": "Development proceeds at a totally identical rate for every individual child.", "D": "Development is solely governed by environmental aspects with zero hereditary influence."}', 'B', 'Development is a predictable, orderly, and continuous process that unfolds across the human lifespan, encompassing progressive physical, mental, and social transformations.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('aa495da9-b39b-4d10-a5c2-fae70c9a578c', @cat_id, @subj_id, 'According to Lev Vygotsky, when children talk aloud to themselves to guide and regulate their own cognitive actions, this speech is called:', '{"A": "Social Speech", "B": "Private Speech", "C": "Egocentric Speech", "D": "Inner Speech"}', 'B', 'Vygotsky termed this ''Private Speech.'' He viewed it as an essential self-regulatory cognitive tool used by children to plan, guide, and monitor their active problem-solving behaviors.', 1.00, 0.00);

INSERT INTO questions (id, category_id, subject_id, question_text, options, correct_option, explanation, marks, negative_marks)
VALUES ('1f05ec27-6a93-428d-b47b-ff5251604ae5', @cat_id, @subj_id, 'The primary focus of Summative Assessment (Yogratmak Mulyankan) is to:', '{"A": "Provide instant formative guidance while a concept is being introduced.", "B": "Evaluate learning outcomes, judge student competency, and assign grades at the end of an instructional unit.", "C": "Modify regular daily lesson plans based on student mood.", "D": "Identify learning disabilities prior to school enrollment."}', 'B', 'Summative assessment is ''assessment of learning.'' It occurs at the conclusion of a specified instructional block (e.g., semester finals) to evaluate cumulative achievement benchmarks and certify performance grades.', 1.00, 0.00);

-- Insert Model Set 2
INSERT INTO model_sets (id, title, description, category_id, vacancy_id, question_ids, time_limit_minutes, total_marks, status)
VALUES ('027ac9ca-963f-49ce-9096-231591b45da4', 'CTET CDP Mock Set 2 (New)', 'Another comprehensive 25-questions mock model MCQ set covering CTET CDP syllabus.', @cat_id, @vac_id, '["50662fb9-9462-4a1a-b19c-293151fa4609", "4ef54e11-c1bb-4061-9845-8ce6a9033568", "db4d9648-d1a8-405b-ba8e-6645a74ac740", "ed6c5c54-f89a-406b-b009-1b2ddc0f9215", "360d6500-ca5d-4e2b-a988-79aab077c7f5", "9aa42237-0393-40ee-a6fe-54bf47eb77aa", "5cb32f68-5403-49f5-84f5-4435b1b89c8d", "493c24b8-55c5-4741-a673-47b2863f7c44", "0890de02-c932-4be9-98ff-1532dde45c7e", "ea46b3a7-42ed-4624-a7f0-088f8fca27a3", "01085758-8659-41a8-9dd0-74c471801390", "fc3310df-a6ce-42c2-8cdc-76491d70f034", "a6450918-5ea4-4a53-b220-d91d748e6386", "a6f83dff-4c52-43e3-93b0-b14342ef6410", "b3394659-174f-4346-812a-4260a5f4c735", "88cc9384-8256-4658-b63f-a3292c755344", "a2268a7a-bb1b-44be-acaa-94d0380c1954", "9d8177c9-55ed-4258-a826-d7cbe0cfd78e", "089f46df-83e8-4375-9f74-0effeb75f8e3", "8a7e61da-ae04-40a2-853b-8fa3b8d5e240", "f89feeac-5dd0-4687-8985-1484157fefd2", "e8ca9d8a-aeb0-49db-b069-21ee4f91e7ea", "6c320511-0875-42bf-8775-307fcb86ea52", "aa495da9-b39b-4d10-a5c2-fae70c9a578c", "1f05ec27-6a93-428d-b47b-ff5251604ae5"]', 30, 25.00, 'published');
